# Generated by Django 4.1.5 on 2023-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_instagram_url_profile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/'),
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(default='Description', max_length=255),
        ),
    ]
