# Generated by Django 4.1.5 on 2023-02-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_cat_img_category_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='description',
        ),
    ]
