# Generated by Django 4.1.5 on 2023-02-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_desc_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='coding', on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
